eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.229.129:8761/eureka/
spring:
  application:
    name: uservice
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accounts
    username: root
    password: ps123456
server:
  port: 8882
